### ISSUE TITLE
Learn the moment matching code by making a new version of `acp_test.py`

### ISSUE THREAD

**Issue by simondgreenhill** [TomBearpark/KIT_code_testing#5]
Hi @kitschwarz, this issue is to familiarize you with the moment matching and welfare calculation code I've been working on for the ag sector.

I've copied over the entire part of the ag repo (which is hosted on gitlab) that is relevant to this project. In this repo, it's in `code/5_crop_shift/`. Please feel free to read the documentation, poke around, try running stuff, etc. 

I've also copied the data you will need to run the code in the tasks below over to our shared Dropbox folder. Note that I didn't copy over every single thing referenced in this part of the repo; if there's something you want to try to run and you don't have the data it references, just let me know.

 We'll discuss the below tasks in detail when we meet tomorrow. Hopefully going through these one by one will help you build some familiarity with the code.

## Tasks
- [ ] Run the script `5_crop_shift/3_algorithm/global_chi/calculate_global_chi.py` and make sure you get the same values as are saved in Dropbox at `KIT_code_test/crop_shift_data/GCP_Reanalysis/AGRICULTURE/4_outputs/3_projections/5_crop_shift/chi/data/chi_global.csv`. As you go through this, take a look at the code in `3_algorithm/function/single_moment/calculate_moment.py` and make sure you understand what's going on.
- [ ] Create a new version of `3_algorithm/acp_test/acp_test.py` that uses the updated moment calculation and matching code that is in `3_algorith/function/single_moment/`. Some additional detail on this:
    - Don't worry about calculating or matching phi or gamma. Just do chi.
    -  To start, move the scripts in `3_algorithm/acp_test/` into a sub-folder called `z_old`. We'll archive those scripts there.
    - You'll need to load and prepare the data differently than is currently being done in the code. See `3_algorithm/global_chi/calculate_global_chi.py` for an example
    - The welfare calculation part should be the same. We can check with Ishan whether we want to calculate the welfare changes using new elasticities or anything like that.
    - Once you're done, compare your values to the outputs in `KIT_code_test/crop_shift_data/GCP_Reanalysis/AGRICULTURE/4_outputs/3_projections/5_crop_shift/acp_test/`. The outputs should be slightly different due to a change in the way we aggregate the crop coverage data, but I expect they will be qualitatively similar.
- [ ]  Create a commit with your new code on the `crop_shift` branch of the agriculture gitlab repo (once you have access to this via your UChicago email)

The one big component of this project that this set of tasks doesn't touch is producing the aggregated crop coverage and potential yield csvs from the raw raster data. Feel free to take a look at the code that does that in `1_cleaning` for starters; we'll come up with a different set of tasks to get you familiar with the inner workings of that code, too.

Let me know if you have any questions!
